# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180320_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='priority_order',
            field=models.IntegerField(default=1, verbose_name='Priority Order'),
        ),
    ]
