# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productimage_priority_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number')),
                ('additional_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Additional phone number')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('working_hours', models.CharField(blank=True, max_length=100, null=True, verbose_name='Working Hours')),
                ('area', models.TextField(blank=True, null=True, verbose_name='Area')),
                ('additional_area_info', models.TextField(blank=True, null=True, verbose_name='Additional area information')),
                ('requisites', models.TextField(blank=True, null=True, verbose_name='Requisites')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
